### ISSUE TITLE
RuntimeError occurs on Rails 5.2.0

### ISSUE THREAD

**Issue by mh61503891** [tcopeland/nullalign#3]
Hi,

I have ran `bundle exec nullalign` on a bare project with rails 5.2.0, but RuntimeError has occurred.

Thanks.

### Steps to reproduce

```sh
$ rails -v
$ Rails 5.2.0
$ rails new .
$ echo "gem 'nullalign'" >> Gemfile
$ bundle install
```

```sh
$ bundle exec nullalign
bundler: failed to load command: nullalign (/Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/bin/nullalign)
RuntimeError: Circular dependency detected while autoloading constant ActiveStorage::Blob::Analyzable
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:500:in `load_missing_constant'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob.rb:21:in `<class:Blob>'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob.rb:16:in `<main>'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `block in load_file'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:653:in `new_constants_in'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:467:in `load_file'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:365:in `block in require_or_load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `load_interlock'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:348:in `require_or_load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:502:in `load_missing_constant'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob/analyzable.rb:5:in `<main>'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `block in load_file'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:653:in `new_constants_in'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:467:in `load_file'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:365:in `block in require_or_load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `load_interlock'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:348:in `require_or_load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:326:in `depend_on'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:242:in `require_dependency'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/lib/nullalign/models.rb:20:in `block (2 levels) in preload_all'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/lib/nullalign/models.rb:19:in `each'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/lib/nullalign/models.rb:19:in `block in preload_all'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/lib/nullalign/models.rb:18:in `each'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/lib/nullalign/models.rb:18:in `preload_all'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/lib/nullalign.rb:10:in `run'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nullalign-0.0.3/bin/nullalign:20:in `<top (required)>'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/bin/nullalign:23:in `load'
  /Users/masayuki/.anyenv/envs/rbenv/versions/2.5.1/bin/nullalign:23:in `<top (required)>'
```

**Comment by dennym** [comment]
in `development.rb` set `config.eager_load` to `true` instead of `false` as a workaround.

Could correlate that every rails `active_*` is a railtie and `active_storage` is an engine.

Edit: nailed it down.
It checks for `MODEL_DIRECTORY_REGEXP = /models/` in the `$LOAD_PATH`. Since also the gems are in the loadpath they get checked against this regexp too.

```bash
/home/denym/.../test_proj/app/models/application_record.rb
/home/denym/.rvm/gems/ruby-2.5.1/gems/activestorage-5.2.1/app/models/active_storage/blob/identifiable.rb
# all the other files that are under /activestorage-5.2.1/app/models
```

All these get `Kernel.require_dependency` and since active_storage has its own required dependencies this leads to the circular thingy.
In detail: I believe that when it gets to `blob/identifiable.rb` its tries to autoload `blob.rb` which has `require_dependency "active_storage/blob/identifiable"` And there you have you your circle. Or in your case  `blob/analyzable.rb`. Whichever comes first.

I guess the cleanest solution would be to just ignore active_storage internal models.

**Comment by tcopeland** [comment]
Thanks for diagnosing and fixing @dennym !

@mh61503891 FYI nullalign 0.0.4 is out now and ran fine on a test Rails 5.2 app.
